### ISSUE TITLE
Can't download the database on ADP website

### ISSUE THREAD

**Issue by ambarion** [lyndonchan/hsn_v1#3]
Hello,

I want to retrain the model of Patch-level Classification CNN, so I searched in the ADP project for the database. And I found the [ADP website](-https://www.dsp.utoronto.ca/projects/ADP/).
I noticed that the database on ADP Website is TO BE released and under Ethics Board Review. May I ask when I can download the database? I've already activated my account on the website. But I can't download the database for the reasons stated before. Or, there is any other way to get the database?

With many thanks

**Comment by lyndonchan** [comment]
@mahdihosseini any thoughts on this?

**Comment by ambarion** [comment]
I got the database from email! Thank you! 

I noticed your comment in #4. That is to say, the pre-trained model of histonet is not trained in the way of [ADP](https://github.com/mahdihosseini/ADP). Instead, you trained the classifier with the network in this paper (the architecture with GMP). Is it right? 

But I find the database input size in[ADP](https://github.com/mahdihosseini/ADP) training code is not actually 224*224, it's 272*272. What method do you use to down-sample the image?

**Comment by lyndonchan** [comment]
If I remember correctly, I used the same training code as in the ADP repo but with the modifications mentioned in the HistoSegNet paper (including the GMP as you mentioned).

As for resizing, I just used the default OpenCV resizing function with cv2.INTER_LINEAR interpolation.

**Comment by ambarion** [comment]
Thanks! I really appreciate your help!
